
import { Teams, MatchData, Formations, PlayerPositionsMap, PlayerCategory, GameRound } from './types';

export const PLAYER_POSITIONS_MAP: PlayerPositionsMap = { 
    "Goalkeeper (GK)": { main: "GK", category: "GK" }, "GK": { main: "GK", category: "GK" },
    "Centre-Back (CB)": { main: "CB", category: "DF" }, "CB": { main: "CB", category: "DF" },
    "Right-Back (RB)": { main: "RB", category: "DF" }, "RB": { main: "RB", category: "DF" },
    "Left-Back (LB)": { main: "LB", category: "DF" }, "LB": { main: "LB", category: "DF" },
    "Sweeper (SW)": { main: "SW", category: "DF" }, "SW": { main: "SW", category: "DF" },
    "Defender (DF)": { main: "DF", category: "DF" },
    "Defensive Midfielder (DM)": { main: "DM", category: "MF" }, "DM": { main: "DM", category: "MF" },
    "Central Midfielder (CM)": { main: "CM", category: "MF" }, "CM": { main: "CM", category: "MF" },
    "Attacking Midfielder (AM)": { main: "AM", category: "MF" }, "AM": { main: "AM", category: "MF" },
    "Left Midfielder (LM)": { main: "LM", category: "MF" }, "LM": { main: "LM", category: "MF" },
    "Right Midfielder (RM)": { main: "RM", category: "MF" }, "RM": { main: "RM", category: "MF" },
    "Midfielder (MF)": { main: "MF", category: "MF" },
    "Left Winger (LW)": { main: "LW", category: "FW" }, "LW": { main: "LW", category: "FW" },
    "Right Winger (RW)": { main: "RW", category: "FW" }, "RW": { main: "RW", category: "FW" },
    "Winger": { main: "W", category: "FW"},
    "Centre-Forward (CF)": { main: "CF", category: "FW" }, "CF": { main: "CF", category: "FW" },
    "Second Striker (SS)": { main: "SS", category: "FW" }, "SS": { main: "SS", category: "FW" },
    "Forward (FW)": { main: "FW", category: "FW" },
    "Wing-Back (RWB)": { main: "RWB", category: "DF" }, "RWB": { main: "RWB", category: "DF" },
    "Wing-Back (LWB)": { main: "LWB", category: "DF" }, "LWB": { main: "LWB", category: "DF" },
};

export function getPlayerCategory(positionString?: string): PlayerCategory { 
    if (!positionString) return "Unknown";

    const positions = positionString.split(/[,/ ]+/); 
    for (const pos of positions) {
        const trimmedPos = pos.trim().toUpperCase();
        if (PLAYER_POSITIONS_MAP[trimmedPos]) return PLAYER_POSITIONS_MAP[trimmedPos].category;
        
        if (trimmedPos === "GK") return "GK";
        if (["CB", "RB", "LB", "SW", "RWB", "LWB", "DF"].includes(trimmedPos)) return "DF";
        if (["DM", "CM", "AM", "LM", "RM", "MF"].includes(trimmedPos)) return "MF";
        if (["CF", "SS", "LW", "RW", "FW"].includes(trimmedPos)) return "FW";
    }
    const lowerPosStr = positionString.toLowerCase();
    if (lowerPosStr.includes("goalkeeper")) return "GK";
    if (lowerPosStr.includes("defender") || lowerPosStr.includes("back") || lowerPosStr.includes("sweeper")) return "DF";
    if (lowerPosStr.includes("midfield") || lowerPosStr.includes("half")) return "MF";
    if (lowerPosStr.includes("forward") || lowerPosStr.includes("striker") || lowerPosStr.includes("winger")) return "FW";
    
    console.warn("Unknown position string for category mapping:", positionString);
    return "Unknown"; 
}


export const TEAMS_RAW_DATA: Teams = { 
    "USA": { name: "United States", squad: [ { number: 1, name: "Tony Meola", posStr: "GK", flavorText: "Captain America between the posts." }, { number: 2, name: "Mike Lapper", posStr: "CB" }, { number: 3, name: "Mike Burns", posStr: "RB" }, { number: 4, name: "Cle Kooiman", posStr: "CB" }, { number: 5, name: "Thomas Dooley", posStr: "DM, SW", flavorText: "German-born defensive stalwart." }, { number: 6, name: "John Harkes", posStr: "LM, CM" }, { number: 7, name: "Hugo Pérez", posStr: "AM" }, { number: 8, name: "Earnie Stewart", posStr: "CF, RM", flavorText: "Goal threat from midfield or attack." }, { number: 9, name: "Tab Ramos", posStr: "RM, AM", flavorText: "Creative spark in the US midfield." }, { number: 10, name: "Roy Wegerle", posStr: "CF" }, { number: 11, name: "Eric Wynalda", posStr: "CF", flavorText: "Scorer of USA's first '94 World Cup goal." }, { number: 12, name: "Juergen Sommer", posStr: "GK" }, { number: 13, name: "Cobi Jones", posStr: "AM, Winger", flavorText: "Speedy winger with iconic hair." }, { number: 14, name: "Frank Klopas", posStr: "CF" }, { number: 15, name: "Joe-Max Moore", posStr: "CF" }, { number: 16, name: "Mike Sorber", posStr: "AM, CM" }, { number: 17, name: "Marcelo Balboa", posStr: "SW, CB", flavorText: "Known for his bicycle kick attempts." }, { number: 18, name: "Brad Friedel", posStr: "GK" }, { number: 19, name: "Claudio Reyna", posStr: "CM", flavorText: "Young talent, future US captain." }, { number: 20, name: "Paul Caligiuri", posStr: "LB, DM" }, { number: 21, name: "Fernando Clavijo", posStr: "RB" }, { number: 22, name: "Alexi Lalas", posStr: "CB", flavorText: "Rockstar defender with a distinctive look." } ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "SUI": { name: "Switzerland", squad: [ { number: 1, name: "Marco Pascolo", posStr: "GK"}, { number: 2, name: "Marc Hottiger", posStr: "RB"}, { number: 3, name: "Yvan Quentin", posStr: "LB"}, { number: 4, name: "Dominique Herr", posStr: "CB"}, { number: 5, name: "Alain Geiger", posStr: "CB"}, { number: 6, name: "Georges Bregy", posStr: "CM", flavorText: "Free-kick specialist." }, { number: 7, name: "Alain Sutter", posStr: "LM", flavorText: "Tricky winger, key to Swiss attack." }, { number: 8, name: "Christophe Ohrel", posStr: "RM"}, { number: 9, name: "Adrian Knup", posStr: "CF"}, { number: 10, name: "Ciriaco Sforza", posStr: "CM", flavorText: "Elegant playmaker." }, { number: 11, name: "Stéphane Chapuisat", posStr: "CF", flavorText: "Prolific Bundesliga striker." }, { number: 12, name: "Stephan Lehmann", posStr: "GK"}, { number: 13, name: "André Egli", posStr: "CB"}, { number: 14, name: "Nestor Subiat", posStr: "CF"}, { number: 15, name: "Marco Grassi", posStr: "CF"}, { number: 16, name: "Thomas Bickel", posStr: "AM"}, { number: 17, name: "Sébastien Fournier", posStr: "DM"}, { number: 18, name: "Martin Rueda", posStr: "SW"}, { number: 19, name: "Jürg Studer", posStr: "CM"}, { number: 20, name: "Patrick Sylvestre", posStr: "DM"}, { number: 21, name: "Thomas Wyss", posStr: "CM"}, { number: 22, name: "Martin Brunner", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "COL": { name: "Colombia", squad: [ { number: 1, name: "Óscar Córdoba", posStr: "GK"}, { number: 2, name: "Andrés Escobar", posStr: "CB", flavorText: "The Gentleman of the Field." }, { number: 3, name: "Alexis Mendoza", posStr: "CB"}, { number: 4, name: "Luis Herrera", posStr: "RB"}, { number: 5, name: "Hernán Gaviria", posStr: "CM"}, { number: 6, name: "Gabriel Jaime Gómez", posStr: "LM"}, { number: 7, name: "Anthony de Ávila", posStr: "CF"}, { number: 8, name: "Hárold Lozano", posStr: "CM"}, { number: 9, name: "Iván Valenciano", posStr: "CF"}, { number: 10, name: "Carlos Valderrama", posStr: "CM", flavorText: "El Pibe, iconic playmaker with golden locks." }, { number: 11, name: "Adolfo Valencia", posStr: "CF", flavorText: "Powerful forward, 'El Tren'." }, { number: 12, name: "Faryd Mondragón", posStr: "GK"}, { number: 13, name: "Néstor Ortiz", posStr: "LB"}, { number: 14, name: "Leonel Álvarez", posStr: "DM"}, { number: 15, name: "Luis Carlos Perea", posStr: "CB"}, { number: 16, name: "Víctor Aristizábal", posStr: "CF"}, { number: 17, name: "Mauricio Serna", posStr: "DM"}, { number: 18, name: "Óscar Cortés", posStr: "MF"}, { number: 19, name: "Freddy Rincón", posStr: "RM", flavorText: "Dynamic midfielder with a powerful shot." }, { number: 20, name: "Wilson Pérez", posStr: "LB"}, { number: 21, name: "Faustino Asprilla", posStr: "CF", flavorText: "Unpredictable and skillful striker." }, { number: 22, name: "José Pazo", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "ROU": { name: "Romania", squad: [ { number: 1, name: "Florin Prunea", posStr: "GK"}, { number: 2, name: "Dan Petrescu", posStr: "RWB, RM", flavorText: "Versatile and energetic wide player." }, { number: 3, name: "Daniel Prodan", posStr: "CB"}, { number: 4, name: "Miodrag Belodedici", posStr: "SW", flavorText: "Elegant sweeper, twice European Cup winner." }, { number: 5, name: "Ioan Lupescu", posStr: "DM"}, { number: 6, name: "Gheorghe Popescu", posStr: "DM, CB", flavorText: "Commanding presence, later Barcelona captain." }, { number: 7, name: "Dorinel Munteanu", posStr: "AM, LM"}, { number: 8, name: "Iulian Chirita", posStr: "DM"}, { number: 9, name: "Florin Răducioiu", posStr: "CF", flavorText: "Well-traveled striker with a keen eye for goal." }, { number: 10, name: "Gheorghe Hagi", posStr: "AM, LM", flavorText: "The Maradona of the Carpathians, a true legend." }, { number: 11, name: "Ilie Dumitrescu", posStr: "CF, LW", flavorText: "Skillful forward, part of Romania's golden generation." }, { number: 12, name: "Bogdan Stelea", posStr: "GK"}, { number: 13, name: "Tibor Selymes", posStr: "LWB, LB"}, { number: 14, name: "Gheorghe Mihali", posStr: "CB"}, { number: 15, name: "Basarab Panduru", posStr: "AM"}, { number: 16, name: "Ion Vlădoiu", posStr: "RW, CF"}, { number: 17, name: "Viorel Moldovan", posStr: "CF"}, { number: 18, name: "Constantin Gâlcă", posStr: "DM"}, { number: 19, name: "Corneliu Papură", posStr: "CB"}, { number: 20, name: "Ovidiu Stîngă", posStr: "RM"}, { number: 21, name: "Marian Ivan", posStr: "CF"}, { number: 22, name: "Ștefan Preda", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "BRA": { name: "Brazil", squad: [ { number: 1, name: "Cláudio Taffarel", posStr: "GK", flavorText: "Reliable shot-stopper for the Seleção." }, { number: 2, name: "Jorginho", posStr: "RB", flavorText: "World-class attacking right-back." }, { number: 3, name: "Ricardo Rocha", posStr: "CB" }, { number: 4, name: "Ronaldão", posStr: "CB" }, { number: 5, name: "Mauro Silva", posStr: "DM", flavorText: "The midfield anchor for Brazil and Deportivo." }, { number: 6, name: "Branco", posStr: "LB", flavorText: "Known for his powerful free-kicks." }, { number: 7, name: "Bebeto", posStr: "CF", flavorText: "Celebrated goals with his 'rock the baby' cradle." }, { number: 8, name: "Dunga", posStr: "CM, DM", flavorText: "Brazil's tough-tackling captain." }, { number: 9, name: "Zinho", posStr: "LW, AM" }, { number: 10, name: "Raí", posStr: "AM", flavorText: "Elegant playmaker, brother of Sócrates." }, { number: 11, name: "Romário", posStr: "CF", flavorText: "Genius in the penalty box, Golden Ball winner." }, { number: 12, name: "Zetti", posStr: "GK" }, { number: 13, name: "Aldair", posStr: "CB", flavorText: "Smooth and composed central defender." }, { number: 14, name: "Cafu", posStr: "RB", flavorText: "Young, energetic full-back, future legend." }, { number: 15, name: "Márcio Santos", posStr: "CB" }, { number: 16, name: "Leonardo Araújo", posStr: "AM, LB" }, { number: 17, name: "Mazinho", posStr: "RM, DM" }, { number: 18, name: "Paulo Sérgio", posStr: "RW" }, { number: 19, name: "Müller", posStr: "SS" }, { number: 20, name: "Ronaldo", posStr: "CF", flavorText: "17-year-old prodigy, future phenomenon." }, { number: 21, name: "Viola", posStr: "CF, LW" }, { number: 22, name: "Gilmar Rinaldi", posStr: "GK" } ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "RUS": { name: "Russia", squad: [ { number: 1, name: "Stanislav Cherchesov", posStr: "GK"}, { number: 2, name: "Dmitri Kuznetsov", posStr: "RB"}, { number: 3, name: "Sergei Gorlukovich", posStr: "CB"}, { number: 4, name: "Dmitri Galiamin", posStr: "LB"}, { number: 5, name: "Yuriy Nikiforov", posStr: "CB"}, { number: 6, name: "Vladislav Ternavsky", posStr: "SW"}, { number: 7, name: "Andrei Piatnitski", posStr: "CM"}, { number: 8, name: "Dmitri Popov", posStr: "LM"}, { number: 9, name: "Oleg Salenko", posStr: "CF", flavorText: "Record 5 goals in one World Cup match!" }, { number: 10, name: "Valeri Karpin", posStr: "RM"}, { number: 11, name: "Vladimir Beschastnykh", posStr: "CF"}, { number: 12, name: "Omari Tetradze", posStr: "RB"}, { number: 13, name: "Aleksandr Borodyuk", posStr: "AM"}, { number: 14, name: "Igor Korneev", posStr: "AM"}, { number: 15, name: "Dmitri Radchenko", posStr: "CF"}, { number: 16, name: "Dmitri Kharine", posStr: "GK", flavorText: "Chelsea's reliable goalkeeper." }, { number: 17, name: "Igor Lediakhov", posStr: "CM"}, { number: 18, name: "Viktor Onopko", posStr: "CB", flavorText: "Russia's influential captain." }, { number: 19, name: "Aleksandr Mostovoi", posStr: "AM", flavorText: "The 'Tsar' of Russian midfield." }, { number: 20, name: "Igor Dobrovolski", posStr: "AM"}, { number: 21, name: "Dmitri Khlestov", posStr: "LB"}, { number: 22, name: "Sergei Yuran", posStr: "CF"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "CMR": { name: "Cameroon", squad: [ { number: 1, name: "Joseph-Antoine Bell", posStr: "GK"}, { number: 2, name: "André Kana-Biyik", posStr: "RB"}, { number: 3, name: "Rigobert Song", posStr: "CB", flavorText: "Young, tenacious defender, future captain." }, { number: 4, name: "Samuel Ekémé", posStr: "LB"}, { number: 5, name: "Victor N'Dip", posStr: "CB"}, { number: 6, name: "Thomas Libiih", posStr: "CM"}, { number: 7, name: "François Omam-Biyik", posStr: "CF", flavorText: "Scorer of the famous goal vs Argentina '90." }, { number: 8, name: "Emile Mbouh", posStr: "CM"}, { number: 9, name: "Roger Milla", posStr: "CF", flavorText: "At 42, the oldest World Cup goalscorer." }, { number: 10, name: "Louis-Paul Mfédé", posStr: "AM"}, { number: 11, name: "Emmanuel Maboang", posStr: "RM"}, { number: 12, name: "Paul Loga", posStr: "DM"}, { number: 13, name: "Raymond Kalla", posStr: "CB"}, { number: 14, name: "Stephen Tataw", posStr: "RB"}, { number: 15, name: "Hans Agbo", posStr: "LB"}, { number: 16, name: "Alphonse Tchami", posStr: "CF"}, { number: 17, name: "Marc-Vivien Foé", posStr: "DM", flavorText: "Young midfielder with immense potential." }, { number: 18, name: "Jean-Pierre Fiala", posStr: "CM"}, { number: 19, name: "David Embé", posStr: "CF"}, { number: 20, name: "Georges Mouyémé", posStr: "CF"}, { number: 21, name: "Thomas N'Kono", posStr: "GK", flavorText: "Legendary Cameroonian goalkeeper." }, { number: 22, name: "Jacques Songo'o", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "SWE": { name: "Sweden", squad: [ { number: 1, name: "Thomas Ravelli", posStr: "GK", flavorText: "Eccentric and brilliant goalkeeper." }, { number: 2, name: "Roland Nilsson", posStr: "RB"}, { number: 3, name: "Patrik Andersson", posStr: "CB", flavorText: "Solid defender, later Bayern Munich star." }, { number: 4, name: "Joachim Björklund", posStr: "CB"}, { number: 5, name: "Roger Ljung", posStr: "LB"}, { number: 6, name: "Stefan Schwarz", posStr: "LM"}, { number: 7, name: "Henrik Larsson", posStr: "RW", flavorText: "Young forward with distinctive dreadlocks." }, { number: 8, name: "Klas Ingesson", posStr: "CM"}, { number: 9, name: "Jonas Thern", posStr: "CM", flavorText: "Sweden's hardworking captain." }, { number: 10, name: "Martin Dahlin", posStr: "CF", flavorText: "Powerful striker, key to Sweden's attack." }, { number: 11, name: "Tomas Brolin", posStr: "SS", flavorText: "Playmaker and goalscorer, Ballon d'Or nominee." }, { number: 12, name: "Lars Eriksson", posStr: "GK"}, { number: 13, name: "Mikael Nilsson", posStr: "RB"}, { number: 14, name: "Pontus Kåmark", posStr: "CB"}, { number: 15, name: "Teddy Lučić", posStr: "CB"}, { number: 16, name: "Anders Limpar", posStr: "LW"}, { number: 17, name: "Stefan Rehn", posStr: "CM"}, { number: 18, name: "Håkan Mild", posStr: "CM"}, { number: 19, name: "Kennet Andersson", posStr: "CF", flavorText: "Tall target man with a knack for crucial goals." }, { number: 20, name: "Magnus Erlingmark", posStr: "AM"}, { number: 21, name: "Jesper Blomqvist", posStr: "LW"}, { number: 22, name: "Magnus Hedman", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "GER": { name: "Germany", squad: [ { number: 1, name: "Bodo Illgner", posStr: "GK", flavorText: "World Cup winning GK from 1990." }, { number: 2, name: "Thomas Strunz", posStr: "DM, RB"}, { number: 3, name: "Andreas Brehme", posStr: "LWB, LB", flavorText: "Scorer of the 1990 World Cup winning penalty." }, { number: 4, name: "Jürgen Kohler", posStr: "CB", flavorText: "Tough-as-nails central defender." }, { number: 5, name: "Thomas Helmer", posStr: "CB, LB"}, { number: 6, name: "Guido Buchwald", posStr: "CB"}, { number: 7, name: "Andreas Möller", posStr: "AM", flavorText: "Dynamic and skillful attacking midfielder." }, { number: 8, name: "Thomas Häßler", posStr: "AM, RM", flavorText: "Diminutive playmaker with great technique." }, { number: 9, name: "Karl-Heinz Riedle", posStr: "CF", flavorText: "Aerial threat and powerful striker." }, { number: 10, name: "Lothar Matthäus", posStr: "SW, CM", flavorText: "German legend, playing in his 4th World Cup." }, { number: 11, name: "Stefan Kuntz", posStr: "CF"}, { number: 12, name: "Andreas Köpke", posStr: "GK"}, { number: 13, name: "Rudi Völler", posStr: "CF", flavorText: "Veteran striker, still a potent force." }, { number: 14, name: "Thomas Berthold", posStr: "CB, RWB"}, { number: 15, name: "Maurizio Gaudino", posStr: "CM"}, { number: 16, name: "Matthias Sammer", posStr: "CM, SW", flavorText: "Future Ballon d'Or winner." }, { number: 17, name: "Martin Wagner", posStr: "LM, LWB"}, { number: 18, name: "Jürgen Klinsmann", posStr: "CF", flavorText: "Energetic striker, known for his diving header." }, { number: 19, name: "Ulf Kirsten", posStr: "CF"}, { number: 20, name: "Stefan Effenberg", posStr: "CM, AM", flavorText: "Talented but controversial midfielder." }, { number: 21, name: "Mario Basler", posStr: "RM, RW"}, { number: 22, name: "Oliver Kahn", posStr: "GK", flavorText: "Young, formidable keeper, future titan." } ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "BOL": { name: "Bolivia", squad: [ { number: 1, name: "Carlos Trucco", posStr: "GK"}, { number: 2, name: "Juan Manuel Peña", posStr: "CB"}, { number: 3, name: "Marco Sandy", posStr: "CB"}, { number: 4, name: "Miguel Rimba", posStr: "RB"}, { number: 5, name: "Gustavo Quinteros", posStr: "CB"}, { number: 6, name: "Carlos Borja", posStr: "CM"}, { number: 7, name: "Mario Pinedo", posStr: "RM"}, { number: 8, name: "José Milton Melgar", posStr: "CM"}, { number: 9, name: "Álvaro Peña", posStr: "CF"}, { number: 10, name: "Erwin Sánchez", posStr: "AM", flavorText: "Platini of the Andes, Bolivia's star." }, { number: 11, name: "Jaime Moreno", posStr: "CF", flavorText: "Young striker, future MLS legend." }, { number: 12, name: "Darío Rojas", posStr: "GK"}, { number: 13, name: "Modesto Soruco", posStr: "LB"}, { number: 14, name: "Mauricio Ramos", posStr: "CM"}, { number: 15, name: "Vladimir Soria", posStr: "DM"}, { number: 16, name: "Luis Cristaldo", posStr: "LM"}, { number: 17, name: "Óscar Sánchez", posStr: "CB"}, { number: 18, name: "William Ramallo", posStr: "CF"}, { number: 19, name: "Marcelo Torrico", posStr: "GK"}, { number: 20, name: "Ramiro Castillo", posStr: "AM"}, { number: 21, name: "Marco Etcheverry", posStr: "AM", flavorText: "El Diablo, skillful and fiery playmaker." }, { number: 22, name: "Julio César Baldivieso", posStr: "AM"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "ESP": { name: "Spain", squad: [ { number: 1, name: "Andoni Zubizarreta", posStr: "GK", flavorText: "Veteran goalkeeper and captain." }, { number: 2, name: "Albert Ferrer", posStr: "RB"}, { number: 3, name: "Jorge Otero", posStr: "LB"}, { number: 4, name: "Francisco Camarasa", posStr: "CB"}, { number: 5, name: "Abelardo Fernández", posStr: "CB"}, { number: 6, name: "Fernando Hierro", posStr: "DM, CB", flavorText: "Versatile defender and midfielder, goal threat." }, { number: 7, name: "Jon Andoni Goikoetxea", posStr: "RM", flavorText: "Speedy and skillful right winger." }, { number: 8, name: "Julen Guerrero", posStr: "AM", flavorText: "Athletic Bilbao's attacking midfield sensation." }, { number: 9, name: "Pep Guardiola", posStr: "DM", flavorText: "Young deep-lying playmaker from Barcelona." }, { number: 10, name: "José Mari Bakero", posStr: "AM"}, { number: 11, name: "Txiki Begiristain", posStr: "LW"}, { number: 12, name: "Sergi Barjuán", posStr: "LB", flavorText: "Attacking left-back from Barcelona." }, { number: 13, name: "Santiago Cañizares", posStr: "GK"}, { number: 14, name: "Juanele", posStr: "CF"}, { number: 15, name: "José Luis Caminero", posStr: "AM, CM", flavorText: "Dynamic midfielder, Spain's standout player in '94." }, { number: 16, name: "Felipe Miñambres", posStr: "CF"}, { number: 17, name: "Voro", posStr: "CB"}, { number: 18, name: "Rafael Alkorta", posStr: "CB"}, { number: 19, name: "Julio Salinas", posStr: "CF", flavorText: "Lanky striker with a knack for important goals." }, { number: 20, name: "Miguel Ángel Nadal", posStr: "CB, DM", flavorText: "The 'Beast', tough tackler." }, { number: 21, name: "Luis Enrique", posStr: "RW, AM", flavorText: "Versatile and energetic attacker." }, { number: 22, name: "Julen Lopetegui", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "KOR": { name: "South Korea", squad: [ { number: 1, name: "Choi In-young", posStr: "GK"}, { number: 2, name: "Chung Jong-son", posStr: "RB"}, { number: 3, name: "Lee Jong-hwa", posStr: "LB"}, { number: 4, name: "Kim Pan-keun", posStr: "CB"}, { number: 5, name: "Park Jung-bae", posStr: "CB"}, { number: 6, name: "Lee Young-jin", posStr: "DM"}, { number: 7, name: "Shin Hong-gi", posStr: "CM"}, { number: 8, name: "Noh Jung-yoon", posStr: "AM"}, { number: 9, name: "Kim Joo-sung", posStr: "CF, AM", flavorText: "Wild Horse, versatile attacker." }, { number: 10, name: "Ko Jeong-woon", posStr: "LW"}, { number: 11, name: "Seo Jung-won", posStr: "RW"}, { number: 12, name: "Choi Young-il", posStr: "CB"}, { number: 13, name: "An Ik-soo", posStr: "RB"}, { number: 14, name: "Choi Dae-shik", posStr: "CM"}, { number: 15, name: "Cho Jin-ho", posStr: "AM"}, { number: 16, name: "Ha Seok-ju", posStr: "LM"}, { number: 17, name: "Gu Sang-bum", posStr: "LB"}, { number: 18, name: "Hwang Sun-hong", posStr: "CF", flavorText: "Prolific striker for the Taegeuk Warriors." }, { number: 19, name: "Choi Moon-sik", posStr: "AM"}, { number: 20, name: "Hong Myung-bo", posStr: "SW, CB", flavorText: "South Korea's legendary libero and captain." }, { number: 21, name: "Park Chul-woo", posStr: "GK"}, { number: 22, name: "Lee Woon-jae", posStr: "GK", flavorText: "Young keeper, future national hero." } ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "ARG": { name: "Argentina", squad: [ { number: 1, name: "Sergio Goycochea", posStr: "GK", flavorText: "Penalty-saving hero of Italia '90." }, { number: 2, name: "Sergio Vázquez", posStr: "CB"}, { number: 3, name: "José Chamot", posStr: "LB"}, { number: 4, name: "Roberto Sensini", posStr: "RB, CB"}, { number: 5, name: "Fernando Redondo", posStr: "DM", flavorText: "Elegant and commanding defensive midfielder." }, { number: 6, name: "Oscar Ruggeri", posStr: "CB", flavorText: "El Cabezón, rugged World Cup '86 winner." }, { number: 7, name: "Claudio Caniggia", posStr: "CF", flavorText: "Son of the Wind, lightning-fast forward." }, { number: 8, name: "José Basualdo", posStr: "RM"}, { number: 9, name: "Gabriel Batistuta", posStr: "CF", flavorText: "Batigol! Powerful striker with a thunderous shot." }, { number: 10, name: "Diego Maradona", posStr: "AM", flavorText: "El Diego, one of football's all-time greatest." }, { number: 11, name: "Ramón Medina Bello", posStr: "CF"}, { number: 12, name: "Luis Islas", posStr: "GK"}, { number: 13, name: "Fernando Cáceres", posStr: "CB"}, { number: 14, name: "Diego Simeone", posStr: "CM", flavorText: "El Cholo, tenacious and fiery midfielder." }, { number: 15, name: "Jorge Borelli", posStr: "CB"}, { number: 16, name: "Hernán Díaz", posStr: "RB"}, { number: 17, name: "Ariel Ortega", posStr: "AM, RW", flavorText: "El Burrito, tricky and skillful attacker." }, { number: 18, name: "Hugo Pérez", posStr: "CM"}, { number: 19, name: "Abel Balbo", posStr: "CF", flavorText: "Reliable goalscorer in Serie A." }, { number: 20, name: "Leonardo Rodríguez", posStr: "AM"}, { number: 21, name: "Alejandro Mancuso", posStr: "DM"}, { number: 22, name: "Norberto Scoponi", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "GRE": { name: "Greece", squad: [ { number: 1, name: "Antonis Minou", posStr: "GK"}, { number: 2, name: "Stratos Apostolakis", posStr: "RB"}, { number: 3, name: "Thanasis Kolitsidakis", posStr: "LB"}, { number: 4, name: "Stelios Manolas", posStr: "CB"}, { number: 5, name: "Ioannis Kalitzakis", posStr: "CB"}, { number: 6, name: "Giotis Tsalouchidis", posStr: "DM"}, { number: 7, name: "Dimitris Saravakos", posStr: "CF", flavorText: "Greece's 'Little Maradona'." }, { number: 8, name: "Nikos Nioblias", posStr: "AM"}, { number: 9, name: "Nikos Machlas", posStr: "CF", flavorText: "Future European Golden Boot winner." }, { number: 10, name: "Tasos Mitropoulos", posStr: "AM"}, { number: 11, name: "Nikos Tsiantakis", posStr: "LM"}, { number: 12, name: "Spiros Maragos", posStr: "CM"}, { number: 13, name: "Vaios Karagiannis", posStr: "RB"}, { number: 14, name: "Vasilis Dimitriadis", posStr: "CF"}, { number: 15, name: "Christos Karkamanis", posStr: "GK"}, { number: 16, name: "Alexis Alexoudis", posStr: "CF"}, { number: 17, name: "Minas Hatzidis", posStr: "RM"}, { number: 18, name: "Kostas Koutroumanos", posStr: "CB"}, { number: 19, name: "Savvas Kofidis", posStr: "CM"}, { number: 20, name: "Elias Atmatsidis", posStr: "GK"}, { number: 21, name: "Alexis Alexandris", posStr: "CF"}, { number: 22, name: "Kyriakos Karataidis", posStr: "LB"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "NGA": { name: "Nigeria", squad: [ { number: 1, name: "Peter Rufai", posStr: "GK", flavorText: "Dodo Mayana, experienced goalkeeper." }, { number: 2, name: "Augustine Eguavoen", posStr: "RB"}, { number: 3, name: "Ben Iroha", posStr: "LB"}, { number: 4, name: "Stephen Keshi", posStr: "CB", flavorText: "The Big Boss, Nigeria's influential captain." }, { number: 5, name: "Uche Okechukwu", posStr: "CB", flavorText: "Gentle Giant, dominant central defender." }, { number: 6, name: "Chidi Nwanu", posStr: "CB"}, { number: 7, name: "Finidi George", posStr: "RW", flavorText: "Exceptional winger, star for Ajax." }, { number: 8, name: "Thompson Oliha", posStr: "CM"}, { number: 9, name: "Rashidi Yekini", posStr: "CF", flavorText: "Goalsfather, Nigeria's all-time top scorer." }, { number: 10, name: "Jay-Jay Okocha", posStr: "AM", flavorText: "So good they named him twice, dazzling skills." }, { number: 11, name: "Emmanuel Amunike", posStr: "LW", flavorText: "African Footballer of the Year '94." }, { number: 12, name: "Samson Siasia", posStr: "CF"}, { number: 13, name: "Emeka Ezeugo", posStr: "DM"}, { number: 14, name: "Daniel Amokachi", posStr: "CF", flavorText: "The Bull, powerful and energetic striker." }, { number: 15, name: "Sunday Oliseh", posStr: "DM", flavorText: "Technically gifted defensive midfielder." }, { number: 16, name: "Alloysius Agu", posStr: "GK"}, { number: 17, name: "Victor Ikpeba", posStr: "CF", flavorText: "Prince of Monaco, pacy forward." }, { number: 18, name: "Efan Ekoku", posStr: "CF"}, { number: 19, name: "Michael Emenalo", posStr: "LB"}, { number: 20, name: "Uche Okafor", posStr: "CB"}, { number: 21, name: "Mutiu Adepoju", posStr: "CM"}, { number: 22, name: "Wilfred Agbonavbare", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "BUL": { name: "Bulgaria", squad: [ { number: 1, name: "Borislav Mikhailov", posStr: "GK", flavorText: "Captain and reliable goalkeeper, known for his wig." }, { number: 2, name: "Emil Kremenliev", posStr: "RB"}, { number: 3, name: "Trifon Ivanov", posStr: "CB", flavorText: "The Wolfman, intimidating defender." }, { number: 4, name: "Tsanko Tsvetanov", posStr: "LB"}, { number: 5, name: "Petar Hubchev", posStr: "CB"}, { number: 6, name: "Zlatko Yankov", posStr: "DM"}, { number: 7, name: "Emil Kostadinov", posStr: "RW, CF", flavorText: "Scored crucial goals to qualify Bulgaria." }, { number: 8, name: "Hristo Stoichkov", posStr: "LW, CF", flavorText: "The Dagger, fiery temper, phenomenal talent, Golden Boot winner." }, { number: 9, name: "Yordan Letchkov", posStr: "AM", flavorText: "Bald-headed magician, scored iconic goal vs Germany." }, { number: 10, name: "Nasko Sirakov", posStr: "CF"}, { number: 11, name: "Daniel Borimirov", posStr: "RM"}, { number: 12, name: "Plamen Nikolov", posStr: "GK"}, { number: 13, name: "Ivaylo Yordanov", posStr: "AM"}, { number: 14, name: "Boncho Genchev", posStr: "CF"}, { number: 15, name: "Nikolay Iliev", posStr: "CB"}, { number: 16, name: "Iliyan Kiryakov", posStr: "LB"}, { number: 17, name: "Petar Mihtarski", posStr: "CF"}, { number: 18, name: "Petar Aleksandrov", posStr: "CF"}, { number: 19, name: "Georgi Georgiev", posStr: "CM"}, { number: 20, name: "Krasimir Balakov", posStr: "AM", flavorText: "Masterful playmaker, part of Bulgaria's magic trio." }, { number: 21, name: "Velko Yotov", posStr: "CF"}, { number: 22, name: "Ivaylo Andonov", posStr: "CF"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "ITA": { name: "Italy", squad: [ { number: 1, name: "Gianluca Pagliuca", posStr: "GK", flavorText: "First keeper sent off in a World Cup final match." }, { number: 2, name: "Luigi Apolloni", posStr: "CB"}, { number: 3, name: "Antonio Benarrivo", posStr: "LB"}, { number: 4, name: "Alessandro Costacurta", posStr: "CB", flavorText: "Elegant defender, part of Milan's great defence." }, { number: 5, name: "Paolo Maldini", posStr: "CB, LB", flavorText: "Il Capitano, one of the greatest defenders ever." }, { number: 6, name: "Franco Baresi", posStr: "SW, CB", flavorText: "Legendary Milan sweeper, made heroic WC final return." }, { number: 7, name: "Lorenzo Minotti", posStr: "CB"}, { number: 8, name: "Roberto Mussi", posStr: "RB"}, { number: 9, name: "Mauro Tassotti", posStr: "RB"}, { number: 10, name: "Roberto Baggio", posStr: "SS, AM", flavorText: "The Divine Ponytail, carried Italy to the final." }, { number: 11, name: "Demetrio Albertini", posStr: "CM", flavorText: "Deep-lying playmaker with superb passing range." }, { number: 12, name: "Luca Marchegiani", posStr: "GK"}, { number: 13, name: "Dino Baggio", posStr: "CM, DM", flavorText: "Not related to Roberto, but a key midfielder." }, { number: 14, name: "Nicola Berti", posStr: "CM"}, { number: 15, name: "Antonio Conte", posStr: "CM", flavorText: "Combative midfielder, future top manager." }, { number: 16, name: "Roberto Donadoni", posStr: "RM, AM"}, { number: 17, name: "Alberico Evani", posStr: "LM, CM"}, { number: 18, name: "Pierluigi Casiraghi", posStr: "CF"}, { number: 19, name: "Daniele Massaro", posStr: "CF", flavorText: "Scored crucial goals for Italy and Milan." }, { number: 20, name: "Giuseppe Signori", posStr: "LW, CF", flavorText: "Prolific Serie A striker with a lethal left foot." }, { number: 21, name: "Gianfranco Zola", posStr: "SS, AM", flavorText: "Magic Box, skillful and creative forward." }, { number: 22, name: "Francesco Toldo", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "IRL": { name: "Republic of Ireland", squad: [ { number: 1, name: "Packie Bonner", posStr: "GK", flavorText: "Hero of Italia '90, iconic Irish keeper." }, { number: 2, name: "Denis Irwin", posStr: "RB", flavorText: "Mr. Reliable, consistent Man Utd full-back." }, { number: 3, name: "Terry Phelan", posStr: "LB"}, { number: 4, name: "Kevin Moran", posStr: "CB"}, { number: 5, name: "Paul McGrath", posStr: "CB", flavorText: "Ooh Aah Paul McGrath! Legendary defender." }, { number: 6, name: "Roy Keane", posStr: "CM", flavorText: "Young, fiery midfielder, future Man Utd captain." }, { number: 7, name: "Andy Townsend", posStr: "CM", flavorText: "Ireland's determined captain." }, { number: 8, name: "Ray Houghton", posStr: "RM", flavorText: "Scorer of famous goals vs England '88 & Italy '94." }, { number: 9, name: "John Aldridge", posStr: "CF", flavorText: "Prolific goalscorer, always gave his all." }, { number: 10, name: "John Sheridan", posStr: "CM"}, { number: 11, name: "Steve Staunton", posStr: "LM, LB"}, { number: 12, name: "Gary Kelly", posStr: "RB"}, { number: 13, name: "Alan Kernaghan", posStr: "CB"}, { number: 14, name: "Phil Babb", posStr: "CB"}, { number: 15, name: "Tommy Coyne", posStr: "CF"}, { number: 16, name: "Tony Cascarino", posStr: "CF"}, { number: 17, name: "Eddie McGoldrick", posStr: "RM"}, { number: 18, name: "Ronnie Whelan", posStr: "CM"}, { number: 19, name: "Alan McLoughlin", posStr: "CM"}, { number: 20, name: "David Kelly", posStr: "CF"}, { number: 21, name: "Jason McAteer", posStr: "RM"}, { number: 22, name: "Alan Kelly Jr.", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "NOR": { name: "Norway", squad: [ { number: 1, name: "Erik Thorstvedt", posStr: "GK", flavorText: "Tottenham Hotspur goalkeeper." }, { number: 2, name: "Gunnar Halle", posStr: "RB"}, { number: 3, name: "Erland Johnsen", posStr: "CB"}, { number: 4, name: "Rune Bratseth", posStr: "CB", flavorText: "Norway's elegant captain and defensive rock." }, { number: 5, name: "Stig Inge Bjørnebye", posStr: "LB", flavorText: "Liverpool left-back known for his crosses." }, { number: 6, name: "Jostein Flo", posStr: "RW, CF", flavorText: "Tall, powerful forward, brother of Tore André." }, { number: 7, name: "Erik Mykland", posStr: "CM", flavorText: "Myggen, diminutive and skillful midfielder." }, { number: 8, name: "Øyvind Leonhardsen", posStr: "CM"}, { number: 9, name: "Jan Åge Fjørtoft", posStr: "CF", flavorText: "Known for his aeroplane goal celebration." }, { number: 10, name: "Kjetil Rekdal", posStr: "CM", flavorText: "Scored crucial penalty vs Mexico." }, { number: 12, name: "Frode Grodås", posStr: "GK"}, { number: 13, name: "Ola By Rise", posStr: "GK"}, { number: 14, name: "Roger Nilsen", posStr: "LB"}, { number: 15, name: "Karl Petter Løken", posStr: "RB"}, { number: 16, name: "Gøran Sørloth", posStr: "CF"}, { number: 17, name: "Dan Eggen", posStr: "CB"}, { number: 18, name: "Alf-Inge Håland", posStr: "DM, RB", flavorText: "Combative player, father of Erling." }, { number: 19, name: "Roar Strand", posStr: "CM"}, { number: 20, name: "Henning Berg", posStr: "CB, RB", flavorText: "Solid defender, later Premier League winner." }, { number: 21, name: "Sigurd Rushfeldt", posStr: "CF"}, { number: 22, name: "Lars Bohinen", posStr: "CM"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "MEX": { name: "Mexico", squad: [ { number: 1, name: "Jorge Campos", posStr: "GK, CF", flavorText: "Flamboyant keeper who also played striker." }, { number: 2, name: "Claudio Suárez", posStr: "CB", flavorText: "El Emperador, Mexico's most capped player." }, { number: 3, name: "Juan de Dios Ramírez Perales", posStr: "CB"}, { number: 4, name: "Ignacio Ambríz", posStr: "DM"}, { number: 5, name: "Ramón Ramírez", posStr: "LM"}, { number: 6, name: "Marcelino Bernal", posStr: "CM"}, { number: 7, name: "Carlos Hermosillo", posStr: "CF"}, { number: 8, name: "Alberto García Aspe", posStr: "AM", flavorText: "Key midfielder and penalty taker." }, { number: 9, name: "Hugo Sánchez", posStr: "CF", flavorText: "Hugol! Legendary Real Madrid striker." }, { number: 10, name: "Luis García Postigo", posStr: "CF", flavorText: "Prolific striker, had a spell at Atlético Madrid." }, { number: 11, name: "Zague (Luis Roberto Alves)", posStr: "LW", flavorText: "Tall forward, son of a Brazilian legend." }, { number: 12, name: "Félix Fernández", posStr: "GK"}, { number: 13, name: "Juan Carlos Chávez", posStr: "CM"}, { number: 14, name: "Joaquín del Olmo", posStr: "CM"}, { number: 15, name: "Missael Espinoza", posStr: "AM"}, { number: 16, name: "Luis Miguel Salvador", posStr: "CF"}, { number: 17, name: "Benjamín Galindo", posStr: "AM"}, { number: 18, name: "José Luis Salgado", posStr: "CB"}, { number: 19, name: "Luis Antonio Valdéz", posStr: "RW"}, { number: 20, name: "Jorge Rodríguez", posStr: "RB"}, { number: 21, name: "Raúl Gutiérrez", posStr: "LB"}, { number: 22, name: "Adrián Chávez", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "BEL": { name: "Belgium", squad: [ { number: 1, name: "Michel Preud'homme", posStr: "GK", flavorText: "Yashin Award winner for best GK in '94." }, { number: 2, name: "Dirk Medved", posStr: "RB"}, { number: 3, name: "Vital Borkelmans", posStr: "LB"}, { number: 4, name: "Philippe Albert", posStr: "CB", flavorText: "Stopper known for marauding runs forward." }, { number: 5, name: "Rudi Smidts", posStr: "LB"}, { number: 6, name: "Lorenzo Staelens", posStr: "DM, CB"}, { number: 7, name: "Franky Van der Elst", posStr: "CM", flavorText: "Reliable and experienced midfielder." }, { number: 8, name: "Luc Nilis", posStr: "CF", flavorText: "Technically gifted striker, great free-kicks." }, { number: 9, name: "Marc Degryse", posStr: "CF, AM"}, { number: 10, name: "Enzo Scifo", posStr: "AM", flavorText: "Elegant playmaker, Belgium's creative heart." }, { number: 11, name: "Alex Czerniatynski", posStr: "CF"}, { number: 12, name: "Filip De Wilde", posStr: "GK"}, { number: 13, name: "Georges Grün", posStr: "CB"}, { number: 14, name: "Michel De Wolf", posStr: "CB, LB"}, { number: 15, name: "Marc Emmers", posStr: "CM, RM"}, { number: 16, name: "Danny Boffin", posStr: "LM"}, { number: 17, name: "Josip Weber", posStr: "CF", flavorText: "Naturalized Croatian, prolific goalscorer." }, { number: 18, name: "Marc Wilmots", posStr: "AM", flavorText: "The Fighting Boar, powerful midfielder." }, { number: 19, name: "Eric Van Meir", posStr: "SW"}, { number: 20, name: "Dany Verlinden", posStr: "GK"}, { number: 21, name: "Stephan Van Der Heyden", posStr: "LM"}, { number: 22, name: "Pascal Renier", posStr: "LB"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "MAR": { name: "Morocco", squad: [ { number: 1, name: "Khalil Azmi", posStr: "GK"}, { number: 2, name: "Nacer Abdellah", posStr: "LB"}, { number: 3, name: "Abdelkrim El Hadrioui", posStr: "LB"}, { number: 4, name: "Tahar El Khalej", posStr: "DM, CB"}, { number: 5, name: "Smahi Triki", posStr: "CB"}, { number: 6, name: "Noureddine Naybet", posStr: "CB", flavorText: "Classy defender, long career at Deportivo." }, { number: 7, name: "Mustapha Hadji", posStr: "AM", flavorText: "Skillful attacker, 1998 African Footballer of the Year." }, { number: 8, name: "Rachid Azzouzi", posStr: "CM"}, { number: 9, name: "Mohammed Chaouch", posStr: "CF"}, { number: 10, name: "Mustapha El Haddaoui", posStr: "AM"}, { number: 11, name: "Rachid Daoudi", posStr: "CM"}, { number: 12, name: "Said Dghay", posStr: "GK"}, { number: 13, name: "Ahmed Bahja", posStr: "CF"}, { number: 14, name: "Ahmed Masbahi", posStr: "RB"}, { number: 15, name: "Arbi Hababi", posStr: "RM"}, { number: 16, name: "Hassan Nader", posStr: "CF"}, { number: 17, name: "Abdelsalam Laghrissi", posStr: "CF"}, { number: 18, name: "Abdelmajid Bouyboud", posStr: "CM"}, { number: 19, name: "Abdelilah Saber", posStr: "RB"}, { number: 20, name: "Hassan Kachloul", posStr: "LM"}, { number: 21, name: "Zakaria Alaoui", posStr: "GK"}, { number: 22, name: "Mustafa El-Idrissi", posStr: "CF"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "NED": { name: "Netherlands", squad: [ { number: 1, name: "Ed de Goey", posStr: "GK"}, { number: 2, name: "Frank de Boer", posStr: "LB, CB", flavorText: "Versatile defender with a sweet left foot." }, { number: 3, name: "Frank Rijkaard", posStr: "CB, DM", flavorText: "Legendary player, returned for one last tournament." }, { number: 4, name: "Ronald Koeman", posStr: "SW, CB", flavorText: "Powerful defender, free-kick and penalty specialist." }, { number: 5, name: "Rob Witschge", posStr: "LM"}, { number: 6, name: "Jan Wouters", posStr: "DM"}, { number: 7, name: "Marc Overmars", posStr: "LW", flavorText: "Lightning-quick winger." }, { number: 8, name: "Wim Jonk", posStr: "CM", flavorText: "Known for his long-range shooting." }, { number: 9, name: "Ronald de Boer", posStr: "AM, CF", flavorText: "Skillful twin brother of Frank." }, { number: 10, name: "Dennis Bergkamp", posStr: "SS, AM", flavorText: "The Non-Flying Dutchman, sublime skill." }, { number: 11, name: "Bryan Roy", posStr: "LW"}, { number: 12, name: "John Bosman", posStr: "CF"}, { number: 13, name: "Edwin van der Sar", posStr: "GK", flavorText: "Young Ajax keeper, future legend." }, { number: 14, name: "Ulrich van Gobbel", posStr: "RB"}, { number: 15, name: "Danny Blind", posStr: "CB", flavorText: "Ajax captain and intelligent defender." }, { number: 16, name: "Arthur Numan", posStr: "LB"}, { number: 17, name: "Gaston Taument", posStr: "RW"}, { number: 18, name: "Stan Valckx", posStr: "CB"}, { number: 19, name: "Peter van Vossen", posStr: "RW"}, { number: 20, name: "Aron Winter", posStr: "RM, CM"}, { number: 21, name: "John de Wolf", posStr: "CB"}, { number: 22, name: "Theo Snelders", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
    "KSA": { name: "Saudi Arabia", squad: [ { number: 1, name: "Mohamed Al-Deayea", posStr: "GK", flavorText: "Legendary Saudi keeper, acrobatic." }, { number: 2, name: "Abdullah Al-Dosari", posStr: "RB"}, { number: 3, name: "Mohammed Al-Khilaiwi", posStr: "CB"}, { number: 4, name: "Abdullah Zubromawi", posStr: "CB"}, { number: 5, name: "Ahmad Madani", posStr: "CB"}, { number: 6, name: "Fuad Anwar Amin", posStr: "CM", flavorText: "Scored Saudi Arabia's first WC goal." }, { number: 7, name: "Fahad Al-Ghesheyan", posStr: "RW"}, { number: 8, name: "Fahad Al-Bishi", posStr: "RM"}, { number: 9, name: "Majed Abdullah", posStr: "CF", flavorText: "Arabian Jewel, prolific striker." }, { number: 10, name: "Saeed Al-Owairan", posStr: "AM", flavorText: "Scored one of the greatest World Cup goals ever." }, { number: 11, name: "Fahad Al-Mehallel", posStr: "CF"}, { number: 12, name: "Sami Al-Jaber", posStr: "CF", flavorText: "Saudi striking legend, played in 4 WCs." }, { number: 13, name: "Mohamed Al-Jawad", posStr: "LB"}, { number: 14, name: "Khaled Al-Muwallid", posStr: "DM"}, { number: 15, name: "Saleh Al-Dawod", posStr: "CB"}, { number: 16, name: "Talal Jebreen", posStr: "CM"}, { number: 17, name: "Yasser Al-Taifi", posStr: "LM"}, { number: 18, name: "Awad Al-Anazi", posStr: "RB"}, { number: 19, name: "Hamzah Saleh", posStr: "CM"}, { number: 20, name: "Hamzah Idris Falatah", posStr: "CF"}, { number: 21, name: "Hussein Al-Sadiq", posStr: "GK"}, { number: 22, name: "Ibrahim Al-Helwah", posStr: "GK"} ].map(p => ({...p, category: getPlayerCategory(p.posStr)}))},
};

export const TEAMS_DATA = TEAMS_RAW_DATA;


export const FORMATIONS: Formations = { 
    "4-4-2": { GK: 1, DF: 4, MF: 4, FW: 2, description: "4 Defenders, 4 Midfielders, 2 Forwards" },
    "3-5-2": { GK: 1, DF: 3, MF: 5, FW: 2, description: "3 Defenders, 5 Midfielders, 2 Forwards" },
    "4-3-3": { GK: 1, DF: 4, MF: 3, FW: 3, description: "4 Defenders, 3 Midfielders, 3 Forwards" },
    "5-3-2": { GK: 1, DF: 5, MF: 3, FW: 2, description: "5 Defenders, 3 Midfielders, 2 Forwards" },
    "4-5-1": { GK: 1, DF: 4, MF: 5, FW: 1, description: "4 Defenders, 5 Midfielders, 1 Forward" },
};

export const MATCHES_DATA: MatchData[] = [
    { id: "M1", group: "A", round: "Group Stage", date: "June 18, 1994", venue: "Pontiac Silverdome, Pontiac", team1: "USA", team2: "SUI", score: "1-1", halfTimeScore: "1-1", goalScorers: [{ team: "SUI", player: "Georges Bregy", minute: "39" }, { team: "USA", player: "Eric Wynalda", minute: "45" }], lineups: {"USA": { starters: [1, 17, 22, 4, 20, 5, 9, 6, 16, 8, 11], formation: "4-4-2" }, "SUI": { starters: [1, 5, 4, 2, 3, 10, 6, 16, 8, 7, 11], formation: "4-5-1" }}, events: [{ type: "Card", team: "SUI", player: "Dominique Herr", card: "Yellow", minute: "26" }] },
    { id: "M2", group: "A", round: "Group Stage", date: "June 18, 1994", venue: "Rose Bowl, Pasadena", team1: "COL", team2: "ROU", score: "1-3", halfTimeScore: "1-2", goalScorers: [{ team: "ROU", player: "Florin Răducioiu", minute: "16" }, { team: "ROU", player: "Gheorghe Hagi", minute: "34" }, { team: "COL", player: "Adolfo Valencia", minute: "43" }, { team: "ROU", player: "Florin Răducioiu", minute: "89" }], lineups: {"COL": {starters: [1,2,15,4,20,14,10,19,6,11,21], formation: "4-4-2"}, "ROU": {starters: [12,4,3,14,6,5,2,10,7,11,9], formation: "3-5-2"}}, events: [] },
    { id: "M3", group: "A", round: "Group Stage", date: "June 22, 1994", venue: "Pontiac Silverdome, Pontiac", team1: "ROU", team2: "SUI", score: "1-4", halfTimeScore: "1-1", goalScorers: [{ team: "SUI", player: "Alain Sutter", minute: "16" }, { team: "ROU", player: "Gheorghe Hagi", minute: "35" }, { team: "SUI", player: "Stéphane Chapuisat", minute: "52" }, { team: "SUI", player: "Adrian Knup", minute: "65" }, { team: "SUI", player: "Adrian Knup", minute: "72" }], lineups: {}, events: [{type: "Card", team: "ROU", player: "Ion Vlădoiu", card: "Red", minute: "73"}] },
    { id: "M4", group: "A", round: "Group Stage", date: "June 22, 1994", venue: "Rose Bowl, Pasadena", team1: "USA", team2: "COL", score: "2-1", halfTimeScore: "1-0", goalScorers: [{ team: "COL", player: "Andrés Escobar", minute: "35", type: "Own Goal (for USA)" }, { team: "USA", player: "Earnie Stewart", minute: "52" }, { team: "COL", player: "Adolfo Valencia", minute: "90" }], lineups: {}, events: [] },
    { id: "M5", group: "A", round: "Group Stage", date: "June 26, 1994", venue: "Stanford Stadium, Stanford", team1: "SUI", team2: "COL", score: "0-2", halfTimeScore: "0-1", goalScorers: [{ team: "COL", player: "Hernán Gaviria", minute: "44" }, { team: "COL", player: "Hárold Lozano", minute: "90" }], lineups: {}, events: [] },
    { id: "M6", group: "A", round: "Group Stage", date: "June 26, 1994", venue: "Rose Bowl, Pasadena", team1: "USA", team2: "ROU", score: "0-1", halfTimeScore: "0-1", goalScorers: [{ team: "ROU", player: "Dan Petrescu", minute: "18" }], lineups: {}, events: [] },
    { id: "M7", group: "B", round: "Group Stage", date: "June 19, 1994", venue: "Rose Bowl, Pasadena", team1: "CMR", team2: "SWE", score: "2-2", halfTimeScore: "1-1", goalScorers: [{ team: "SWE", player: "Roger Ljung", minute: "8" }, { team: "CMR", player: "David Embé", minute: "31" }, { team: "CMR", player: "François Omam-Biyik", minute: "47" }, { team: "SWE", player: "Martin Dahlin", minute: "75" }]},
    { id: "M8", group: "B", round: "Group Stage", date: "June 20, 1994", venue: "Stanford Stadium, Stanford", team1: "BRA", team2: "RUS", score: "2-0", halfTimeScore: "1-0", goalScorers: [{ team: "BRA", player: "Romário", minute: "26" }, { team: "BRA", player: "Raí", minute: "52", type: "Penalty" }]},
    { id: "M9", group: "B", round: "Group Stage", date: "June 24, 1994", venue: "Stanford Stadium, Stanford", team1: "BRA", team2: "CMR", score: "3-0", halfTimeScore: "1-0", goalScorers: [{ team: "BRA", player: "Romário", minute: "39" }, { team: "BRA", player: "Márcio Santos", minute: "66" }, { team: "BRA", player: "Bebeto", minute: "73" }], events: [{type: "Card", team: "CMR", player: "Rigobert Song", card: "Red", minute: "63"}] },
    { id: "M10", group: "B", round: "Group Stage", date: "June 24, 1994", venue: "Pontiac Silverdome, Pontiac", team1: "SWE", team2: "RUS", score: "3-1", halfTimeScore: "1-1", goalScorers: [{ team: "RUS", player: "Oleg Salenko", minute: "4", type: "Penalty" }, { team: "SWE", player: "Tomas Brolin", minute: "37", type: "Penalty" }, { team: "SWE", player: "Martin Dahlin", minute: "59" }, { team: "SWE", player: "Martin Dahlin", minute: "81" }], events: [{type: "Card", team: "RUS", player: "Sergei Gorlukovich", card: "Red", minute: "49"}] },
    { id: "M11", group: "B", round: "Group Stage", date: "June 28, 1994", venue: "Stanford Stadium, Stanford", team1: "RUS", team2: "CMR", score: "6-1", halfTimeScore: "3-0", goalScorers: [{ team: "RUS", player: "Oleg Salenko", minute: "15" }, { team: "RUS", player: "Oleg Salenko", minute: "41" }, { team: "RUS", player: "Oleg Salenko", minute: "44", type: "Penalty" }, { team: "CMR", player: "Roger Milla", minute: "46" }, { team: "RUS", player: "Oleg Salenko", minute: "72" }, { team: "RUS", player: "Oleg Salenko", minute: "75" }, { team: "RUS", player: "Dmitri Radchenko", minute: "81" }]},
    { id: "M12", group: "B", round: "Group Stage", date: "June 28, 1994", venue: "Pontiac Silverdome, Pontiac", team1: "BRA", team2: "SWE", score: "1-1", halfTimeScore: "0-1", goalScorers: [{ team: "SWE", player: "Kennet Andersson", minute: "23" }, { team: "BRA", player: "Romário", minute: "46" }]},
    { id: "M13", group: "C", round: "Group Stage", date: "June 17, 1994", venue: "Soldier Field, Chicago", team1: "GER", team2: "BOL", score: "1-0", halfTimeScore: "0-0", goalScorers: [{ team: "GER", player: "Jürgen Klinsmann", minute: "61" }], events: [{type: "Card", team: "BOL", player: "Marco Etcheverry", card: "Red", minute: "82"}] },
    { id: "M14", group: "C", round: "Group Stage", date: "June 17, 1994", venue: "Cotton Bowl, Dallas", team1: "ESP", team2: "KOR", score: "2-2", halfTimeScore: "0-0", goalScorers: [{ team: "ESP", player: "Julio Salinas", minute: "51" }, { team: "ESP", player: "Jon Andoni Goikoetxea", minute: "55" }, { team: "KOR", player: "Hong Myung-bo", minute: "85" }, { team: "KOR", player: "Seo Jung-won", minute: "90" }], events: [{type: "Card", team: "ESP", player: "Miguel Ángel Nadal", card: "Red", minute: "25"}] },
    { id: "M15", group: "C", round: "Group Stage", date: "June 21, 1994", venue: "Soldier Field, Chicago", team1: "GER", team2: "ESP", score: "1-1", halfTimeScore: "0-1", goalScorers: [{ team: "ESP", player: "Jon Andoni Goikoetxea", minute: "14" }, { team: "GER", player: "Jürgen Klinsmann", minute: "48" }]},
    { id: "M16", group: "C", round: "Group Stage", date: "June 23, 1994", venue: "Foxboro Stadium, Foxborough", team1: "KOR", team2: "BOL", score: "0-0", halfTimeScore: "0-0", goalScorers: [], events: [{type: "Card", team: "BOL", player: "Luis Cristaldo", card: "Red", minute: "82"}] },
    { id: "M17", group: "C", round: "Group Stage", date: "June 27, 1994", venue: "Cotton Bowl, Dallas", team1: "GER", team2: "KOR", score: "3-2", halfTimeScore: "3-0", goalScorers: [{ team: "GER", player: "Jürgen Klinsmann", minute: "12" }, { team: "GER", player: "Karl-Heinz Riedle", minute: "20" }, { team: "GER", player: "Jürgen Klinsmann", minute: "37" }, { team: "KOR", player: "Hwang Sun-hong", minute: "52" }, { team: "KOR", player: "Hong Myung-bo", minute: "63" }], events: [{type: "Card", team: "GER", player: "Stefan Effenberg", card: "Red", minute: "75"}] },
    { id: "M18", group: "C", round: "Group Stage", date: "June 27, 1994", venue: "Soldier Field, Chicago", team1: "BOL", team2: "ESP", score: "1-3", halfTimeScore: "0-1", goalScorers: [{ team: "ESP", player: "Pep Guardiola", minute: "19", type: "Penalty" }, { team: "BOL", player: "Erwin Sánchez", minute: "67" }, { team: "ESP", player: "José Luis Caminero", minute: "70" }, { team: "ESP", player: "José Luis Caminero", minute: "71" }]},
    { id: "M19", group: "D", round: "Group Stage", date: "June 21, 1994", venue: "Foxboro Stadium, Foxborough", team1: "ARG", team2: "GRE", score: "4-0", halfTimeScore: "2-0", goalScorers: [{ team: "ARG", player: "Gabriel Batistuta", minute: "2" }, { team: "ARG", player: "Gabriel Batistuta", minute: "44" }, { team: "ARG", player: "Diego Maradona", minute: "60" }, { team: "ARG", player: "Gabriel Batistuta", minute: "90", type: "Penalty" }]},
    { id: "M20", group: "D", round: "Group Stage", date: "June 21, 1994", venue: "Cotton Bowl, Dallas", team1: "NGA", team2: "BUL", score: "3-0", halfTimeScore: "2-0", goalScorers: [{ team: "NGA", player: "Rashidi Yekini", minute: "21" }, { team: "NGA", player: "Daniel Amokachi", minute: "43" }, { team: "NGA", player: "Emmanuel Amunike", minute: "55" }]},
    { id: "M21", group: "D", round: "Group Stage", date: "June 25, 1994", venue: "Foxboro Stadium, Foxborough", team1: "ARG", team2: "NGA", score: "2-1", halfTimeScore: "2-1", goalScorers: [{ team: "NGA", player: "Samson Siasia", minute: "8" }, { team: "ARG", player: "Claudio Caniggia", minute: "21" }, { team: "ARG", player: "Claudio Caniggia", minute: "28" }]},
    { id: "M22", group: "D", round: "Group Stage", date: "June 26, 1994", venue: "Soldier Field, Chicago", team1: "BUL", team2: "GRE", score: "4-0", halfTimeScore: "1-0", goalScorers: [{ team: "BUL", player: "Hristo Stoichkov", minute: "5", type: "Penalty" }, { team: "BUL", player: "Hristo Stoichkov", minute: "55", type: "Penalty" }, { team: "BUL", player: "Yordan Letchkov", minute: "65" }, { team: "BUL", player: "Daniel Borimirov", minute: "90" }]},
    { id: "M23", group: "D", round: "Group Stage", date: "June 30, 1994", venue: "Cotton Bowl, Dallas", team1: "ARG", team2: "BUL", score: "0-2", halfTimeScore: "0-0", goalScorers: [{ team: "BUL", player: "Hristo Stoichkov", minute: "61" }, { team: "BUL", player: "Nasko Sirakov", minute: "90+3" }]},
    { id: "M24", group: "D", round: "Group Stage", date: "June 30, 1994", venue: "Foxboro Stadium, Foxborough", team1: "GRE", team2: "NGA", score: "0-2", halfTimeScore: "0-1", goalScorers: [{ team: "NGA", player: "Finidi George", minute: "45+2" }, { team: "NGA", player: "Daniel Amokachi", minute: "90+5" }]},
    { id: "M25", group: "E", round: "Group Stage", date: "June 18, 1994", venue: "Giants Stadium, East Rutherford", team1: "ITA", team2: "IRL", score: "0-1", halfTimeScore: "0-1", goalScorers: [{ team: "IRL", player: "Ray Houghton", minute: "11" }]},
    { id: "M26", group: "E", round: "Group Stage", date: "June 19, 1994", venue: "RFK Stadium, Washington D.C.", team1: "NOR", team2: "MEX", score: "1-0", halfTimeScore: "0-0", goalScorers: [{ team: "NOR", player: "Kjetil Rekdal", minute: "84" }]},
    { id: "M27", group: "E", round: "Group Stage", date: "June 23, 1994", venue: "Giants Stadium, East Rutherford", team1: "ITA", team2: "NOR", score: "1-0", halfTimeScore: "0-0", goalScorers: [{ team: "ITA", player: "Dino Baggio", minute: "69" }], events: [{type: "Card", team: "ITA", player: "Gianluca Pagliuca", card: "Red", minute: "21"}] },
    { id: "M28", group: "E", round: "Group Stage", date: "June 24, 1994", venue: "Citrus Bowl, Orlando", team1: "MEX", team2: "IRL", score: "2-1", halfTimeScore: "1-0", goalScorers: [{ team: "MEX", player: "Luis García Postigo", minute: "42" }, { team: "MEX", player: "Luis García Postigo", minute: "65" }, { team: "IRL", player: "John Aldridge", minute: "84" }], events: [{type: "Card", team: "MEX", player: "Luis García Postigo", card: "Red", minute: "57"}] },
    { id: "M29", group: "E", round: "Group Stage", date: "June 28, 1994", venue: "Giants Stadium, East Rutherford", team1: "IRL", team2: "NOR", score: "0-0", halfTimeScore: "0-0", goalScorers: []},
    { id: "M30", group: "E", round: "Group Stage", date: "June 28, 1994", venue: "RFK Stadium, Washington D.C.", team1: "ITA", team2: "MEX", score: "1-1", halfTimeScore: "0-0", goalScorers: [{ team: "ITA", player: "Daniele Massaro", minute: "48" }, { team: "MEX", player: "Marcelino Bernal", minute: "57" }]},
    { id: "M31", group: "F", round: "Group Stage", date: "June 19, 1994", venue: "Citrus Bowl, Orlando", team1: "BEL", team2: "MAR", score: "1-0", halfTimeScore: "1-0", goalScorers: [{ team: "BEL", player: "Marc Degryse", minute: "11" }]},
    { id: "M32", group: "F", round: "Group Stage", date: "June 20, 1994", venue: "RFK Stadium, Washington D.C.", team1: "NED", team2: "KSA", score: "2-1", halfTimeScore: "0-1", goalScorers: [{ team: "KSA", player: "Fuad Anwar Amin", minute: "18" }, { team: "NED", player: "Wim Jonk", minute: "50" }, { team: "NED", player: "Gaston Taument", minute: "86" }]},
    { id: "M33", group: "F", round: "Group Stage", date: "June 25, 1994", venue: "Citrus Bowl, Orlando", team1: "BEL", team2: "NED", score: "1-0", halfTimeScore: "0-0", goalScorers: [{ team: "BEL", player: "Philippe Albert", minute: "65" }]},
    { id: "M34", group: "F", round: "Group Stage", date: "June 25, 1994", venue: "Giants Stadium, East Rutherford", team1: "KSA", team2: "MAR", score: "2-1", halfTimeScore: "2-1", goalScorers: [{ team: "KSA", player: "Sami Al-Jaber", minute: "7", type: "Penalty" }, { team: "MAR", player: "Mohammed Chaouch", minute: "26" }, { team: "KSA", player: "Fuad Anwar Amin", minute: "45" }]},
    { id: "M35", group: "F", round: "Group Stage", date: "June 29, 1994", venue: "Citrus Bowl, Orlando", team1: "MAR", team2: "NED", score: "1-2", halfTimeScore: "0-1", goalScorers: [{ team: "NED", player: "Dennis Bergkamp", minute: "43" }, { team: "MAR", player: "Hassan Nader", minute: "47" }, { team: "NED", player: "Bryan Roy", minute: "77" }]},
    { id: "M36", group: "F", round: "Group Stage", date: "June 29, 1994", venue: "RFK Stadium, Washington D.C.", team1: "BEL", team2: "KSA", score: "0-1", halfTimeScore: "0-1", goalScorers: [{ team: "KSA", player: "Saeed Al-Owairan", minute: "5" }]},
    { id: "M37", round: "Round of 16", date: "July 2, 1994", venue: "Soldier Field, Chicago", team1: "GER", team2: "BEL", score: "3-2", halfTimeScore: "3-1", goalScorers: [{team:"GER", player:"Rudi Völler", minute:"6"}, {team:"BEL", player:"Georges Grün", minute:"8"}, {team:"GER", player:"Jürgen Klinsmann", minute:"11"}, {team:"GER", player:"Rudi Völler", minute:"38"}, {team:"BEL", player:"Philippe Albert", minute:"90"}]},
    { id: "M38", round: "Round of 16", date: "July 2, 1994", venue: "RFK Stadium, Washington D.C.", team1: "ESP", team2: "SUI", score: "3-0", halfTimeScore: "1-0", goalScorers: [{team:"ESP", player:"Fernando Hierro", minute:"15"}, {team:"ESP", player:"Luis Enrique", minute:"74"}, {team:"ESP", player:"Txiki Begiristain", minute:"86", type:"Penalty"}] },
    { id: "M39", round: "Round of 16", date: "July 3, 1994", venue: "Cotton Bowl, Dallas", team1: "KSA", team2: "SWE", score: "1-3", halfTimeScore: "0-1", goalScorers: [{team:"SWE", player:"Martin Dahlin", minute:"6"}, {team:"SWE", player:"Kennet Andersson", minute:"51"}, {team:"KSA", player:"Fahad Al-Ghesheyan", minute:"85"}, {team:"SWE", player:"Kennet Andersson", minute:"88"}] },
    { id: "M40", round: "Round of 16", date: "July 3, 1994", venue: "Rose Bowl, Pasadena", team1: "ROU", team2: "ARG", score: "3-2", halfTimeScore: "2-1", goalScorers: [{team:"ROU", player:"Ilie Dumitrescu", minute:"11"}, {team:"ARG", player:"Gabriel Batistuta", minute:"16", type:"Penalty"}, {team:"ROU", player:"Ilie Dumitrescu", minute:"18"}, {team:"ROU", player:"Gheorghe Hagi", minute:"58"}, {team:"ARG", player:"Abel Balbo", minute:"75"}] },
    { id: "M41", round: "Round of 16", date: "July 4, 1994", venue: "Citrus Bowl, Orlando", team1: "NED", team2: "IRL", score: "2-0", halfTimeScore: "2-0", goalScorers: [{team:"NED", player:"Dennis Bergkamp", minute:"11"}, {team:"NED", player:"Wim Jonk", minute:"41"}] },
    { id: "M42", round: "Round of 16", date: "July 4, 1994", venue: "Stanford Stadium, Stanford", team1: "BRA", team2: "USA", score: "1-0", halfTimeScore: "0-0", goalScorers: [{ team: "BRA", player: "Bebeto", minute: "72" }], events: [{ type: "Card", team: "BRA", player: "Leonardo Araújo", card: "Red", minute: "43" }, { type: "Card", team: "USA", player: "Fernando Clavijo", card: "Red", minute: "85" }] },
    { id: "M43", round: "Round of 16", date: "July 5, 1994", venue: "Foxboro Stadium, Foxborough", team1: "NGA", team2: "ITA", score: "1-2", halfTimeScore: "1-0", extraTimeScore: "1-2", goalScorers: [{team:"NGA", player:"Emmanuel Amunike", minute:"25"}, {team:"ITA", player:"Roberto Baggio", minute:"88"}, {team:"ITA", player:"Roberto Baggio", minute:"102", type:"Penalty"}], events: [{type:"Card", team:"ITA", player:"Gianfranco Zola", card:"Red", minute:"75"}] },
    { id: "M44", round: "Round of 16", date: "July 5, 1994", venue: "Giants Stadium, East Rutherford", team1: "MEX", team2: "BUL", score: "1-1", halfTimeScore: "1-1", extraTimeScore: "1-1", penalties: "BUL 3-1 MEX", goalScorers: [{team:"BUL", player:"Hristo Stoichkov", minute:"6"}, {team:"MEX", player:"Alberto García Aspe", minute:"18", type:"Penalty"}] },
    { id: "M45", round: "Quarter-finals", date: "July 9, 1994", venue: "Foxboro Stadium, Foxborough", team1: "ITA", team2: "ESP", score: "2-1", halfTimeScore: "1-0", goalScorers: [{team:"ITA", player:"Dino Baggio", minute:"25"}, {team:"ESP", player:"José Luis Caminero", minute:"58"}, {team:"ITA", player:"Roberto Baggio", minute:"88"}] },
    { id: "M46", round: "Quarter-finals", date: "July 9, 1994", venue: "Cotton Bowl, Dallas", team1: "NED", team2: "BRA", score: "2-3", halfTimeScore: "0-0", goalScorers: [{team:"BRA", player:"Romário", minute:"53"}, {team:"BRA", player:"Bebeto", minute:"63"}, {team:"NED", player:"Dennis Bergkamp", minute:"64"}, {team:"NED", player:"Aron Winter", minute:"76"}, {team:"BRA", player:"Branco", minute:"81"}] },
    { id: "M47", round: "Quarter-finals", date: "July 10, 1994", venue: "Giants Stadium, East Rutherford", team1: "BUL", team2: "GER", score: "2-1", halfTimeScore: "0-0", goalScorers: [{team:"GER", player:"Lothar Matthäus", minute:"47", type:"Penalty"}, {team:"BUL", player:"Hristo Stoichkov", minute:"75"}, {team:"BUL", player:"Yordan Letchkov", minute:"78"}] },
    { id: "M48", round: "Quarter-finals", date: "July 10, 1994", venue: "Stanford Stadium, Stanford", team1: "ROU", team2: "SWE", score: "2-2", halfTimeScore: "0-0", extraTimeScore: "2-2", penalties: "SWE 5-4 ROU", goalScorers: [{team:"SWE", player:"Tomas Brolin", minute:"78"}, {team:"ROU", player:"Florin Răducioiu", minute:"88"}, {team:"ROU", player:"Florin Răducioiu", minute:"101"}, {team:"SWE", player:"Kennet Andersson", minute:"115"}] },
    { id: "M49", round: "Semi-finals", date: "July 13, 1994", venue: "Giants Stadium, East Rutherford", team1: "BUL", team2: "ITA", score: "1-2", halfTimeScore: "1-2", goalScorers: [{team:"ITA", player:"Roberto Baggio", minute:"21"}, {team:"ITA", player:"Roberto Baggio", minute:"25"}, {team:"BUL", player:"Hristo Stoichkov", minute:"44", type:"Penalty"}] },
    { id: "M50", round: "Semi-finals", date: "July 13, 1994", venue: "Rose Bowl, Pasadena", team1: "SWE", team2: "BRA", score: "0-1", halfTimeScore: "0-0", goalScorers: [{team:"BRA", player:"Romário", minute:"80"}] },
    { id: "M51", round: "Third Place Play-off", date: "July 16, 1994", venue: "Rose Bowl, Pasadena", team1: "SWE", team2: "BUL", score: "4-0", halfTimeScore: "4-0", goalScorers: [{team:"SWE", player:"Tomas Brolin", minute:"8"}, {team:"SWE", player:"Håkan Mild", minute:"30"}, {team:"SWE", player:"Henrik Larsson", minute:"37"}, {team:"SWE", player:"Kennet Andersson", minute:"39"}] },
    { id: "M52", round: "Final", date: "July 17, 1994", venue: "Rose Bowl, Pasadena", team1: "BRA", team2: "ITA", score: "0-0", halfTimeScore: "0-0", extraTimeScore: "0-0", penalties: "BRA 3-2 ITA", goalScorers: [] , events: [{ type: "Info", text: "Brazil won 3-2 on penalties."}]}
];


export const ALL_MATCHES_SORTED: MatchData[] = [...MATCHES_DATA].sort((a, b) => {
    const dateA = new Date(a.date);
    const dateB = new Date(b.date);

    const dateDiff = dateA.getTime() - dateB.getTime();
    if (dateDiff !== 0) return dateDiff;
    
    const numA = parseInt(a.id.substring(1), 10);
    const numB = parseInt(b.id.substring(1), 10);
    return numA - numB;
});


export const GROUP_DEFINITIONS: { [key: string]: string[] } = { 
    "A": ["USA", "SUI", "COL", "ROU"],
    "B": ["BRA", "RUS", "CMR", "SWE"],
    "C": ["GER", "BOL", "ESP", "KOR"],
    "D": ["ARG", "GRE", "NGA", "BUL"],
    "E": ["ITA", "IRL", "NOR", "MEX"],
    "F": ["BEL", "MAR", "NED", "KSA"]
};

export const MAX_STARTERS = 11;
export const MAX_SUBS = 7;

export const GAME_ROUNDS: GameRound[] = [
    { name: "Group Stage - Round 1", matchIDs: ["M1", "M2", "M7", "M8", "M13", "M14", "M19", "M20", "M25", "M26", "M31", "M32"], isGroupStage: true },
    { name: "Group Stage - Round 2", matchIDs: ["M3", "M4", "M9", "M10", "M15", "M16", "M21", "M22", "M27", "M28", "M33", "M34"], isGroupStage: true },
    { name: "Group Stage - Round 3", matchIDs: ["M5", "M6", "M11", "M12", "M17", "M18", "M23", "M24", "M29", "M30", "M35", "M36"], isGroupStage: true },
    { name: "Round of 16", matchIDs: ["M37", "M38", "M39", "M40", "M41", "M42", "M43", "M44"], isGroupStage: false },
    { name: "Quarter-finals", matchIDs: ["M45", "M46", "M47", "M48"], isGroupStage: false },
    { name: "Semi-finals", matchIDs: ["M49", "M50"], isGroupStage: false },
    { name: "Finals", matchIDs: ["M51", "M52"], isGroupStage: false }, 
];
